[server]
# Comma-separated list.
allowed_ips = localhost, 192.168.50.0/24

# Use "none" (case-insensitive) to disable public URL
public_base_url = none

search_engine_url = https://duckduckgo.com/?q={}

browser_width = 720
browser_height = 1280

headless = false

port = 5049

use_memory_screenshots = true
max_memory_screenshots = 10