[server]
# Comma-separated list. It is recommended to include your public IP if hosting for external access.
allowed_ips = 127.0.0.1, localhost

# Use "none" (case-insensitive) to disable public URL
public_base_url = none

search_engine_url = https://duckduckgo.com/?q={}

browser_width = 720
browser_height = 1280

headless = false

port = 5049